services:
  app-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: nestjs-app-prod
    environment:
      - PORT=8001
      - NODE_ENV=production
    ports:
      - '8001:8001'
    # depends_on:
    #   - postgres_db
    volumes:
      - ./src:/usr/src/app/src

  # postgres_db:
  #   image: postgres
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=root
  #     - POSTGRES_DB=nestjsblog
  #   container_name: nestjs-postgres
  #   volumes:
  #     - ./pgdata:/var/lib/postgresql/data
  #   ports:
  #     - '5432:5432'
