PATCH http://localhost:8000/posts/
Content-Type: application/json

{
    "id":8,
    "title":"Test Title with JavaScript",
    "postType":"post",
    "status":"draft",
    "content":"test content with JavaScript",
    "tags":[1,2]
}