POST http://localhost:8000/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjI1LCJlbWFpbCI6Ik1hcmtNaXJhQGVtYWlsLmNvbSIsImlhdCI6MTczMTY5MTQwOSwiZXhwIjoxNzMxNjk1MDA5LCJhdWQiOiJsb2NhbGhvc3Q6ODAwMCIsImlzcyI6ImxvY2FsaG9zdDo4MDAwIn0.RX-Qo6dK1g1UKMN6_Th0juihIs9EKqvLrMGK5IfVng0

{
    "firstName" : "Jonny",
    "lastName" : "Coelho",
    "email":"Jonny@email.com",
    "password":"JonnyCoelho@1"
}

POST http://localhost:8000/users/create-many
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjI1LCJlbWFpbCI6Ik1hcmtNaXJhQGVtYWlsLmNvbSIsImlhdCI6MTczMTUyMDk0MywiZXhwIjoxNzMxNTI0NTQzLCJhdWQiOiJsb2NhbGhvc3Q6ODAwMCIsImlzcyI6ImxvY2FsaG9zdDo4MDAwIn0.FrFUamVWFNQXhno9YXkJERpJuVdzAFEzwik321vDQoA
{
  "users":  
  [
    {
    "firstName" : "Test Query",
    "lastName" : "Runner",
    "email":"queryRunner@email.com",
    "password":"queryRunner@1"
    },
    {
    "firstName" : "Test Query 2",
    "lastName" : "Runner 2",
    "email":"queryRunner2@email.com",
    "password":"queryRunner@2"
    }
  ]
}